#pragma once
/* This was generated by capra_micro_comm.
* DO NOT EDIT
*/
#include <capra_comm.h>

struct Void
{
};

struct Vector2D
{
    efloat_t x;
    efloat_t y;
};

struct State
{
    eboolean_t state;
};

Void ledOn(Void);
Void ledOff(Void);
Void setLedState(State);
BaseFunction_ptr commands[] = {
    new Function<Void, Void>(&ledOn),
    new Function<Void, Void>(&ledOff),
    new Function<Void, State>(&setLedState),
};
#define COMMANDS_COUNT 3